name: Birthday Automation

on:

  workflow_dispatch:

  schedule:

    - cron: "30 2 * * *"

jobs:

  birthday:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python app/main.py

        env:

          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

          GOOGLE_SERVICE_ACCOUNT: service.json

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}